version = 1

[[analyzers]]
name = "python"
enabled = false

[[analyzers]]
name = "secrets"
enabled = false

[[analyzers]]
name = "docker"
enabled = false

[[transformers]]
name = "autopep8"
enabled = false

[[transformers]]
name = "isort"
enabled = false
