version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

  [[analyzers.exclude_patterns]]
  pattern = ".venv/**"
  
  [[analyzers.exclude_patterns]]
  pattern = "venv/**"
  
  [[analyzers.exclude_patterns]]
  pattern = "**/site-packages/**"

[[analyzers]]
name = "secrets"
enabled = false

[[analyzers]]
name = "docker"
enabled = false

[[transformers]]
name = "autopep8"
enabled = false

[[transformers]]
name = "isort"
enabled = false
